### ISSUE TITLE
Update to latest open release

### ISSUE THREAD

**Issue by EliJDonahue** [ArasLabs/refresh-from-database#4]
Test and update to support Aras 11 SP12.

**Comment by PremalBhagat** [comment]
Tested and Updated for latest open release Aras 11SP12. Package is compatible with Aras 11SP12. Tested on browsers Internet Explorer 11, Firefox 52, Chrome 69.

**Comment by cgillis-aras** [comment]
This project was tested on SP12 in 875b72ccc50f58e46759cea0fc54a58975aec855 and then on SP15 in a6639b2e3f6c16648bd241560e52d13bb10cb536.
